### ISSUE TITLE
You are not authorized to access the resource

### ISSUE THREAD

**Issue by raymondfx** [bcgov/issuer-kit#208]
<img width="1419" alt="Screenshot 2020-07-13 at 23 10 47" src="https://user-images.githubusercontent.com/26685061/87348902-282f2f00-c55e-11ea-8962-889949002549.png">

**Comment by raymondfx** [comment]
managed to get around this with npm install

**Comment by dinbtechit** [comment]
ran into the same example issue. I'm running this in the docker container locally... How did you manage to resolve this?

**Comment by esune** [comment]
> managed to get around this with npm install

Where did you run `npm install`? If running `./manage build` and `./manage start` as per instructions the docker build will perform that step, so it is really not required.

**Comment by dinbtechit** [comment]
I was able to start it in the dev mode.  `./manage start-dev` 

I ran `npm install` in api, issuer-admin and issuer-web. But for some reason, I couldn't start it in local mode.

@esune  - What machine do you use for local development?

**Comment by esune** [comment]
@dinbtechit that is correct. Local mode is configured to require an invite in order to access `issuer-web`, so you would have to follow the steps described above - dev mode may be configured to bypass this authorization in order to make development easier. All these settings can be tweaked by updating configurations appropriately, as described here: https://github.com/bcgov/issuer-kit/blob/main/docs/ConfiguringIssuerKit.md
