### ISSUE TITLE
Add issue credential endpoint protection

### ISSUE THREAD

**Issue by swcurran** [bcgov/issuer-kit#237]
Per discussion today on the DTS Standup, add protection to the "issue credential" endpoint to prevent issuance without whatever authentications are configured into the application.  I'm not sure technically how to protect the endpoint, but from a business perspective, the following apply:

- if the service is protected by the need to proof an OIDC credential from a configured IdP (e.g. vc-authn, GitHub, IDIR, etc.), do not allow issuance without such a token.
- if the service is protected by the need to have a valid email invitation token, do not allow issuance without such a token.
- if the service is unprotected (e.g. "Unverified Person"), no issuance protection is necessary.

As noted, I'm not sure of the technical challenge of implementing those protections, but if it is difficult, let's discuss.

Thanks

**Comment by esune** [comment]
The new rules will only be able to protect the `issue-credential` endpoints, since the services will have no way of knowing whether a request for  connection is legitimate or not in case of unprotected instances of the issuer web application.

I am planning for request to the `issue-credential` endpoints to work this way:
- submit the invitation token *OR*
- submit a valid authorization header containing a token issued by the trusted authority *OR*
- specify a schema id that is whitelisted (unprotected) in the controller configuration.

I am not yet sure it will be possible to maintain the current flexibility configuring each instance if complex checks (e.g.: id token + invite token) need to be implemented, so I will leave this considerations on hold until the main part of the authorization framework is in place.
