### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by zhangbobo2023** [bcgov/issuer-kit#336]
root@iZ2vcekg07cyl1x2opxonzZ:~/issuer-kit# ./docker/manage start
./docker/manage: line 5: getDockerHost: command not found
The client id and/or secret for the integration of GitHub as IDP for Keycloak were not provided.
Please set the GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET environment variables to use GitHub as your IDP.
To get your  client id/secret combination, please visit: https://github.com/settings/developers
Press Ctrl+C now to stop, or wait to proceed without GitHub integration.
Building tails-server
ERROR: error fetching: fatal: Couldn't find remote ref master
: exit status 128

downloading the latest code,  an error when build tails-server,  how to solve ?

**Comment by esune** [comment]
This happens when [this command](https://github.com/bcgov/issuer-kit/blob/f33bd803faaa23120112cebfde92c4c85cf30ffc/docker/manage#L4) fails. Please make sure you can download the script at the target url and your version of curl (possibly git bash, as it would come embedded with it) is up-to-date. Older versions of git bash seem to cause issues.

**Comment by zhangbobo2023** [comment]
ok~
