### ISSUE TITLE
Show only the editable fields in the survey

### ISSUE THREAD

**Issue by swcurran** [bcgov/issuer-kit#369]
Not sure if this is possible, but...

It would be nice if the Survey JS form showed only the editable fields from the form vs. all of them.  Even better would be to have a list of the uneditable claim/value pairs above the form, and the form have only the editable ones.

This links to the issue #368 about bypassing the form entirely when there is nothing to edit.

**Comment by esune** [comment]
I believe this will require non-minor development and, possibly, getting away from SurveyJS altogether as an option.

Currently, any field that is not displayed by SurveyJS will not be added to the survey's final payload, so we would need to come up with custom state management to create the credential request with or without survey being filled.
#368 and this would definitely fit very well together as part of the same change as the other change will require the same type of state management in order to both determine whether there is something that requires filling or not.

**Comment by swcurran** [comment]
Thanks for the assessment.  We'll leave this one on hold for now and wait until we get a hard need for this.
