### ISSUE TITLE
Unable to issue credentials

### ISSUE THREAD

**Issue by sorincocorada** [bcgov/issuer-kit#399]
While trying to connect with the issuer in demo mode, after scanning the QR code I am always getting "Something went wrong" from the Trinsic Wallet. esatus and Lissi wallet also report similar errors. The smartphone is able to access the issuer-web.

**Comment by esune** [comment]
Hi @sorincocorada, I will have to take a look as it's been a while since the last time I used the project in demo mode.
In the meantime, can you please check/confirm that:
* your `ngrok` is running
* your `ngrok` session has not timed out (i.e.: the tunnel is still active)
* does your console show any errors when starting up the project?

**Comment by esune** [comment]
@sorincocorada I run through the demo and was able to receive a credential using both eSatus and Lissi. Trinsic is throwing an error for me as well, but I am unable to determine what is wrong as it seems to be on the wallet end.

For eSatus (and Trinsic) make sure you select BCGov Test Ledger (or BCovrin Test) as ledgers, otherwise you won;t be able to establish a connection.

I am using Android, and had to reset my wallet apps in order for them to work after upgrading to Android 12 - which mobile OS are you running? If on Android, you may want to start fresh as well if the issue is not with the `ngrok` tunnel.

**Comment by sorincocorada** [comment]
In the end I was able to issue credentials using eSatus and Lissi. Problem was related to ngrok.
Thank you for your support.
