### ISSUE TITLE
No issuer-web log in screen.

### ISSUE THREAD

**Issue by Laderlappen** [bcgov/issuer-kit#442]
I'm trying to run the issuer-kit in demo mode. If I navigate to http://localhost:8082/ to access the issuer-web page it shows the unauthorized screen and no option to log in. I can't find a way to log in any other way.

**Comment by esune** [comment]
@Laderlappen you will need to go to `http://localhost:8081`, sign-in with the admin credentials (`issuer-admin`/`issuer-admin`) and generate an invite for yourself in order to be able to use the issuer.

Alternatively, you can run the demo without requiring an invite after setting [this flag](https://github.com/bcgov/issuer-kit/blob/edee62127449f125ae428587f09087bcf9722f7b/docker/issuer-web/config/web/config.json#L10) to `false`.

**Comment by Laderlappen** [comment]
Thanks @esune, I thought I was probably missing something. When I create an invite in the admin page no email is sent to the email address that I specify there. So I'll have to debug why that is. The flag will be super useful in the mean time.

**Comment by esune** [comment]
That is because in demo mode emails go to a `maildev` sink, see https://github.com/bcgov/issuer-kit#demo-mode - you can find the email there. Closing this issue as resolved.
